version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"    # Porta para o Laravel (backend)
      - "5173:5173"    # Porta para o Vite (frontend)
    volumes:
      - .:/app    # Mapeia a pasta local para o diretório do contêiner
      - /app/vendor # Evita a substituição dos arquivos de dependências do Composer
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    command: ["bash", "-c", "php-fpm & npm run dev"]  # Comando para rodar o Laravel e o Vite simultaneamente

  # TODO: Adicionar o container do MySQL ao arquivo docker-compose.yml
  # não esta criando o
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: $$WAsdsa&&447
#       MYSQL_DATABASE: db_project_laravel  # Nome do banco de dados
#       MYSQL_USER: root  # Nome do usuário
#       MYSQL_PASSWORD: $$WAsdsa&&447  # Senha do usuário
#     ports:
#       - "3306:3306"  # Porta do MySQL
#     volumes:
#       - mysql_data:/var/lib/mysql  # Persistência de dados
#     networks:
#       - app-network

# # Volumes para persistência de dados
# volumes:
#   mysql_data:

# Redes para comunicação entre os containers
networks:
  app-network:
    driver: bridge
